name: Main branch CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4

    -
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: "adopt"

    -
      name: Setup Gradle and caching
      uses: gradle/gradle-build-action@v2

    -
      name: Gradle build
      run: |
        ./gradlew clean build -x test

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
      name: Docker build and push
      uses: docker/build-push-action@v5
      with:
        file: Product.Dockerfile
        context: .
        push: true
        tags: duhanmo/lostark-info-api:latest
    -
      name: Create secret to file into runner server
      run: echo "${{ secrets.APPLICATION_PRODUCT_PROPERTIES }}" > ./application-product.properties

    -
      name: Send properties file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "./application-product.properties"
        target: "/home/ec2-user/secret"

    -
      name: Send docker-compose.api.yml to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "./docker/docker-compose.api.yml"
        target: "/home/ec2-user"
    -
      name: Send deploy file to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "./script/deploy.sh"
        target: "/home/ec2-user"

    -
      name: Execute docker pull and deploy.sh
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo docker pull duhanmo/lostark-info-api:latest
          chmod 777 /home/ec2-user/script/deploy.sh
          /home/ec2-user/script/deploy.sh
          docker image prune -f